language: bash
services: docker
jobs:
  include:
    - stage: test
      name: "unit tests"
      script: docker run --rm -v `pwd`:/app mcr.microsoft.com/dotnet/core/sdk:3.0-alpine3.9 sh -c "cd /app; dotnet test"
    - stage: test
      name: "build package"
      script: docker run --rm -v `pwd`:/app mcr.microsoft.com/dotnet/core/sdk:3.0-alpine3.9 sh -c "cd /app; dotnet build"
    - stage: test
      name: "postman tests"
      language: node_js
      node_js: 
        - "12"
      script:
        - TAG=`git rev-parse --short=4 ${TRAVIS_COMMIT}`
        - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_LOGIN" --password-stdin
        - docker build . -t fossapps/micro.auth --build-arg VERSION=$TAG
        - docker-compose -f ./docker-compose.ci.yml up -d
        - cd ./Micro.Auth.UnitTest/ExternalTests
        - sh postman_tests.sh
        - docker tag fossapps/micro.auth fossapps/micro.auth:$TAG
        - docker push fossapps/micro.auth:$TAG
    - stage: deploy
      name: "semantic-release"
      language: node_js
      node_js: 
        - "12"
      script:
        - npm i -g semantic-release @semantic-release/exec
        - semantic-release
