version: '3'
services:
  api:
    image: fossapps/micro.auth
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=ci
  postgres:
    image: postgres:11-alpine
    ports:
      - 15433:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=starter
      - POSTGRES_DB=starter_db
  key_store:
    image: fossapps/micro.keystore:1.5.0
    volumes:
      - ./.docker-configs/keystore/appsettings.json:/app/appsettings.json
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_ADMIN_USER=cyberhck
      - INFLUXDB_ADMIN_PASSWORD=secret
      - INFLUXDB_DB=monitoring
    ports:
      - 8086:8086 # http api
      - 8083:8083 # admin interface
