version: '3'
services:
  key_store:
    image: fossapps/micro.keystore:1.6.0
    ports:
      - 15000:15000
    environment:
      - ASPNETCORE_URLS=http://+:15000
    volumes:
      - ./.docker-configs/keystore/appsettings.json:/app/appsettings.json
  postgres:
    image: postgres:11-alpine
    ports:
      - 15433:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=starter
      - POSTGRES_DB=starter_db
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_ADMIN_USER=cyberhck
      - INFLUXDB_ADMIN_PASSWORD=secret
      - INFLUXDB_DB=monitoring
    ports:
      - 8086:8086 # http api
      - 8083:8083 # admin interface

  chronograf:
    image: chronograf
    environment:
      - influxdb-url=influxdb:8086
    ports:
      - 18888:8888

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,raintank-worldping-app,digrich-bubblechart-panel,corpglory-progresslist-panel,flant-statusmap-panel
    ports:
      - 3000:3000
  adminer:
      image: adminer
      ports:
        - 8081:8080
  kibana:
    image: kibana:7.6.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_PASSWORD=mynewpassword
      - ELASTICSEARCH_USERNAME=elastic
      - xpack.security.enabled=true
    depends_on:
      - es
    ports:
      - 5601:5601
  es:
    image: elasticsearch:7.6.0
    environment:
      - ELASTIC_PASSWORD=mynewpassword
      - node.name=es01
      - xpack.security.enabled=true
      - discovery.type=single-node
      - cluster.name=ohio-cluster
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true

    ports:
      - 9200:9200
      - 9300:9300
