// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FossApps.KeyStore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class KeyCreatedResponse
    {
        /// <summary>
        /// Initializes a new instance of the KeyCreatedResponse class.
        /// </summary>
        public KeyCreatedResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KeyCreatedResponse class.
        /// </summary>
        public KeyCreatedResponse(string body = default(string), string id = default(string))
        {
            Body = body;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public string Body { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

    }
}
