// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace FossApps.KeyStore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PingResponse
    {
        /// <summary>
        /// Initializes a new instance of the PingResponse class.
        /// </summary>
        public PingResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PingResponse class.
        /// </summary>
        public PingResponse(string ping = default(string))
        {
            Ping = ping;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ping")]
        public string Ping { get; set; }

    }
}
